---
title: "Leonardo Egidi"
description: Website of the statistician Leonardo Egidi
baseurl: "" # Se stai pubblicando in una sottocartella, imposta il baseurl come /subfolder
url: "https://leoegidi.github.io" # URL del tuo sito
paginate:            5
permalink:           pretty

author:
  name: Leonardo Egidi
  email: legidi@units.it
  twitter_username: tuo_twitter
  github_username: LeoEgidi
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
navigation:
  #- title: Home
  #  url: /
  - title: "About"
    url: /about
  #- title: Research
  #  url: /research/
  - title: Publications
    url: /publications/
  #- title: Teaching
  #  url: /teaching/
  #- title: CV
  #  url: /cv/
# show_downloads: "true"
permalink: /:categories/:title/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
#  - node_modules
# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
