---
title: "Leonardo Egidi - Statistician"
description: "Leonardo Egidi - Assistant Professor of Statistics at the University of Trieste"
baseurl: "" # Se stai pubblicando in una sottocartella, imposta il baseurl come /subfolder
url: "https://leoegidi.github.io" # URL del tuo sito
paginate:            5
permalink:           pretty


author:
  name: Leonardo Egidi
  email: legidi@units.it
  twitter_username: tuo_twitter
  github_username: LeoEgidi
# remote_theme: pages-themes/tactile@v0.2.0

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

navigation:
  - title: Home
    url: /
  - title: Research
    url: /leonardo-egidi-research/
  - title: Publications
    url: /leonardo-egidi-publications/
  - title: Software
    url: /leonardo-egidi-software/
  - title: Teaching
    url: /leonardo-egidi-teaching/
  - title: Students
    url: /leonardo-egidi-students/
  - title: egBayes Lab
    url: /leonardo-egidi-lab/
# show_downloads: "true"



exclude:
  - README.md
#  - Gemfile
#  - Gemfile.lock
#  - node_modules

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
